name: Cria Override.yaml

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  generate-override:
    runs-on: ubuntu-latest
    environment: variaveis  # Garante que as vari치veis do Environment "variaveis" sejam carregadas
    steps:
      - name: Checkout do reposit칩rio
        uses: actions/checkout@v4

      - name: Print name Repo
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          echo "Nome do reposit칩rio: $REPO_NAME"
      
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Criar arquivo JSON com vari치veis do Environment
        run: echo '${{ toJson(vars) }}' > vars.json

      - name: Criar override.yaml dinamicamente
        run: |
          echo "secretProviderClass:" > override.yaml
          echo "  data:" >> override.yaml

          VAR_LIST=$(jq -r 'keys[]' vars.json)

          for VAR in $VAR_LIST; do
            VALUE=$(jq -r --arg key "$VAR" '.[$key]' vars.json)
            echo "    - objectName: $VAR" >> override.yaml
            echo "      key: $VAR" >> override.yaml
          done

          echo "  parameters:" >> override.yaml
          echo "    objects: |" >> override.yaml

          for VAR in $VAR_LIST; do
            echo "      - objectName: \"/eks/docket-documento-ai/\${ENVIRONMENT}/$VAR\"" >> override.yaml
            echo "        objectAlias: $VAR" >> override.yaml
            echo "        objectType: \"ssmparameter\"" >> override.yaml
          done

          echo "env:" >> override.yaml

          for VAR in $VAR_LIST; do
            echo "  - name: $VAR" >> override.yaml
            echo "    valueFrom:" >> override.yaml
            echo "      secretKeyRef:" >> override.yaml
            echo "        name: docket-documento-ai-\${ENVIRONMENT}-keys" >> override.yaml
            echo "        key: $VAR" >> override.yaml
          done

      - name: Exibir override.yaml gerado
        run: cat override.yaml
